language: php
dist: xenial
sudo: required

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - docker

php:
  - 7.3

env:
  global:
    - DRUPAL_BASE_URL="http://127.0.0.1:8080"
    - XDEBUG_MODE=coverage
    - DB_DUMP_URL="https://doc-0k-9s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/s5492ucsck2eo68l6b06o35ogls3dp1a/1617869325000/11410537201823817928/*/1P90R4ldTDUWmsPp-RkjMeg-MQfEcnpFq?e=download"
  matrix:
    - JOB=job:check-coding-standards
    - JOB=job:run-unit-tests
    - JOB=job:run-behat-tests

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer --verbose install

before_script:
  - cp .travis/RoboFile.php .

script:
  - vendor/bin/robo $JOB

after_success:
  - test $JOB = "job:run-unit-tests" && travis_retry php vendor/bin/php-coveralls -v
